CREATE TABLE Users (
	id VARCHAR(255) NOT NULL,
	screen_id VARCHAR(255) NOT NULL,
	name VARCHAR(255) NOT NULL,
	image VARCHAR(255) NOT NULL,
	profile VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;